const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Plugins.Button,
		C3.Plugins.video,
		C3.Plugins.AJAX,
		C3.Plugins.Share,
		C3.Plugins.FileSystem,
		C3.Plugins.BinaryData,
		C3.Plugins.Date,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetHAlign,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Acts.LoadLayoutTextures,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Exps.len,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.FileSystem.Cnds.IsSupported,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.FileSystem.Acts.AddAcceptType,
		C3.Plugins.FileSystem.Acts.ShowSaveFilePicker,
		C3.Plugins.FileSystem.Cnds.OnPickerComplete,
		C3.Plugins.FileSystem.Acts.WriteBinaryFile,
		C3.Plugins.video.Acts.SetX,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Browser: 0},
	{button_2: 0},
	{button_3: 0},
	{button_04: 0},
	{bg_2: 0},
	{button_5: 0},
	{naming: 0},
	{player: 0},
	{pressRight: 0},
	{chat_03: 0},
	{layout3_1: 0},
	{dire_1: 0},
	{dire: 0},
	{button_6: 0},
	{layout3_2: 0},
	{layout3_3: 0},
	{choo_1: 0},
	{choo_2: 0},
	{pressLeft: 0},
	{chat_02: 0},
	{layout3_3_1: 0},
	{gamerule01: 0},
	{butterfly: 0},
	{hole_01: 0},
	{hole_02: 0},
	{hole_03: 0},
	{hole_04: 0},
	{hole_05: 0},
	{hole_06: 0},
	{hole_07: 0},
	{hole_08: 0},
	{DragDrop: 0},
	{ans_01: 0},
	{ans_02: 0},
	{ans_03: 0},
	{ans_04: 0},
	{ans_05: 0},
	{ans_06: 0},
	{ans_07: 0},
	{ans_08: 0},
	{layout3_4_1: 0},
	{layout3_3_2: 0},
	{layout3_4_2: 0},
	{layout3_5: 0},
	{bg_1: 0},
	{layout3_6: 0},
	{layout3_7: 0},
	{L5_1: 0},
	{L5_2: 0},
	{L4: 0},
	{layout8_1: 0},
	{button_06_1: 0},
	{layout8_2: 0},
	{gamerule02: 0},
	{ani_03: 0},
	{chat_03_2: 0},
	{layout11_1: 0},
	{ani_04: 0},
	{button_07_1: 0},
	{gamerule03: 0},
	{layout15_1: 0},
	{ani_05: 0},
	{layout_19: 0},
	{answer: 0},
	{ani_06: 0},
	{gamerule04: 0},
	{gamerule05: 0},
	{layout24: 0},
	{layout25: 0},
	{ani_17: 0},
	{layout27: 0},
	{gamerule06: 0},
	{sea_game: 0},
	{layout30: 0},
	{tip_01: 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{button_07_2: 0},
	{tip_02: 0},
	{tip_03: 0},
	{tip_04: 0},
	{tip_05: 0},
	{tip_06: 0},
	{tip_07: 0},
	{tip_08: 0},
	{"8方向": 0},
	{邊界約束: 0},
	{dog_window: 0},
	{dog_control: 0},
	{dog_panel: 0},
	{dog_bg: 0},
	{dog_factory: 0},
	{dog_river: 0},
	{dog_animal: 0},
	{dog_farmer: 0},
	{dog_land: 0},
	{dog_storm: 0},
	{market_bg: 0},
	{Solid: 0},
	{market_floor: 0},
	{market_sun: 0},
	{Platform: 0},
	{market_girl: 0},
	{market_shop5: 0},
	{market_shop4: 0},
	{market_shop3: 0},
	{market_flag: 0},
	{market_shop2: 0},
	{market_shop1: 0},
	{button_16_1: 0},
	{button_16_1_2: 0},
	{market_game1: 0},
	{market_game1_roof: 0},
	{market_game1_girl: 0},
	{market_game1_Q1: 0},
	{market_game1_Q1d: 0},
	{market_game1_Q1c: 0},
	{market_game1_Q1a: 0},
	{market_game1_accurate: 0},
	{Bullet: 0},
	{market_game1_bullet: 0},
	{market_game1_Q1b: 0},
	{market_game1_Q2: 0},
	{market_game1_Q2a: 0},
	{market_game1_Q2b: 0},
	{market_game1_Q2c: 0},
	{market_game1_Q2d: 0},
	{market_game1_Q3: 0},
	{market_game1_Q3a: 0},
	{market_game1_Q3b: 0},
	{market_game1_Q3c: 0},
	{market_game1_Q3d: 0},
	{market_game1_Q4: 0},
	{market_game1_Q4a: 0},
	{market_game1_Q4b: 0},
	{market_game1_Q4c: 0},
	{market_game1_Q4d: 0},
	{market_game1_Q5a: 0},
	{market_game1_Q5: 0},
	{market_game1_Q5b: 0},
	{market_game1_Q5c: 0},
	{market_game1_Q5d: 0},
	{dog_trash: 0},
	{dog_storm_teach: 0},
	{dog_factory_teach: 0},
	{dog_animal_teach: 0},
	{dog_land_teach: 0},
	{dog_farmer_teach: 0},
	{dog_river_teach: 0},
	{dog_trash_teach: 0},
	{button_go_home: 0},
	{button_16_2: 0},
	{button_16_3: 0},
	{button_16_4: 0},
	{button_16_5: 0},
	{button_1: 0},
	{video: 0},
	{button_14_1: 0},
	{market_game1_ans1: 0},
	{market_game1_ans2: 0},
	{market_game1_ans3: 0},
	{market_game1_ans4: 0},
	{market_game1_ans5: 0},
	{market_game1_finish: 0},
	{button_17_back: 0},
	{market_game1_tip: 0},
	{button_17_next_1: 0},
	{button_17_next_2: 0},
	{button_17_next_3: 0},
	{button_17_next_4: 0},
	{market_game2_bg: 0},
	{market_game2_tip: 0},
	{button_17_1: 0},
	{market_game2_Q1: 0},
	{market_game2_Q1a: 0},
	{market_game2_Q1b: 0},
	{market_game2_Q1c: 0},
	{market_game2_Q1d: 0},
	{market_game2_ans1: 0},
	{button_17_1_next1: 0},
	{market_game2_Q2: 0},
	{market_game2_Q2a: 0},
	{market_game2_Q2b: 0},
	{market_game2_Q2c: 0},
	{market_game2_Q2d: 0},
	{button_17_1_next2: 0},
	{market_game2_ans2: 0},
	{market_game2_Q3: 0},
	{market_game2_Q3a: 0},
	{market_game2_Q3b: 0},
	{market_game2_Q3c: 0},
	{market_game2_Q3d: 0},
	{button_17_1_next3: 0},
	{market_game2_ans3: 0},
	{market_game2_Q4a: 0},
	{market_game2_Q4: 0},
	{market_game2_Q4b: 0},
	{market_game2_Q4c: 0},
	{market_game2_Q4d: 0},
	{market_game2_ans4: 0},
	{button_17_1_next4: 0},
	{market_game2_finish: 0},
	{button_17_1_back: 0},
	{market_game3_Q1: 0},
	{market_game3_Q1a: 0},
	{market_game3_Q1b: 0},
	{market_game3_Q1c: 0},
	{market_game3_Q1d: 0},
	{market_game3_ans1: 0},
	{market_game3_Q2: 0},
	{market_game3_Q2a: 0},
	{market_game3_Q2b: 0},
	{market_game3_Q2c: 0},
	{market_game3_Q2d: 0},
	{market_game3_ans2: 0},
	{button_17_2next1: 0},
	{market_game3_Q3: 0},
	{button_17_2next2: 0},
	{button_17_2next3: 0},
	{market_game3_Q3a: 0},
	{market_game3_Q3b: 0},
	{market_game3_Q3c: 0},
	{market_game3_Q3d: 0},
	{market_game3_ans3: 0},
	{market_game3_Q4: 0},
	{market_game3_Q4a: 0},
	{market_game3_Q4b: 0},
	{market_game3_Q4c: 0},
	{market_game3_Q4d: 0},
	{button_17_2next4: 0},
	{market_game3_ans4: 0},
	{market_game3_Q5: 0},
	{market_game3_Q5a: 0},
	{market_game3_Q5b: 0},
	{market_game3_Q5c: 0},
	{market_game3_Q5d: 0},
	{market_game3_ans5: 0},
	{button_17_2next5: 0},
	{market_game3_finish: 0},
	{button_17_2_back: 0},
	{market_game3_tip: 0},
	{button_17_2: 0},
	{butterfly_finish: 0},
	{button_07_3: 0},
	{button_14_2: 0},
	{dog_finish: 0},
	{market_game4_Q1: 0},
	{market_game4_Q1a: 0},
	{market_game4_Q1b: 0},
	{market_game4_Q1c: 0},
	{market_game4_Q1d: 0},
	{market_game4_Q1e: 0},
	{market_game5_bg: 0},
	{market_game5_Q1a: 0},
	{market_game5_Q1b: 0},
	{market_game5_Q1c: 0},
	{market_game5_Q1d: 0},
	{market_game5_Q1e: 0},
	{market_game5_Q1f: 0},
	{market_game5_Q1g: 0},
	{market_game5_ans1: 0},
	{button_17_4next1: 0},
	{market_game5_Q2a: 0},
	{market_game5_Q2b: 0},
	{market_game5_Q2c: 0},
	{market_game5_ans2: 0},
	{button_17_4next2: 0},
	{button_17_4next3: 0},
	{market_game5_Q3a: 0},
	{market_game5_Q3b: 0},
	{market_game5_Q3c: 0},
	{market_game5_ans3: 0},
	{market_game4_ans_but: 0},
	{market_game4_ans: 0},
	{button_17_3next1: 0},
	{button_17_3next2: 0},
	{button_17_3next3: 0},
	{button_17_3next4: 0},
	{market_game4_Q2: 0},
	{market_game4_Q2a: 0},
	{market_game4_Q2b: 0},
	{market_game4_Q2c: 0},
	{market_game4_Q2d: 0},
	{market_game4_Q2e: 0},
	{market_game4_ans2_but: 0},
	{market_game4_ans2: 0},
	{market_game4_Q3: 0},
	{market_game4_Q3a: 0},
	{market_game4_Q4b: 0},
	{market_game4_Q3c: 0},
	{market_game4_Q3d: 0},
	{market_game4_Q3e: 0},
	{market_game4_ans3_but: 0},
	{market_game4_ans3: 0},
	{market_game4_Q4: 0},
	{market_game4_Q4a: 0},
	{market_game4_Q4c: 0},
	{market_game4_Q4d: 0},
	{market_game4_Q4e: 0},
	{market_game4_ans4_but: 0},
	{market_game4_ans4: 0},
	{market_game4_Q5: 0},
	{market_game4_Q5a: 0},
	{market_game4_Q5b: 0},
	{market_game4_Q5c: 0},
	{market_game4_Q5d: 0},
	{market_game4_Q5e: 0},
	{market_game4_ans5_but: 0},
	{market_game4_ans5: 0},
	{button_17_3next5: 0},
	{market_game4_Q3b: 0},
	{button_17_3: 0},
	{button_17_3_back: 0},
	{market_game4_finish: 0},
	{market_game4_tip: 0},
	{button_17_4: 0},
	{button_17: 0},
	{button_17_next_5: 0},
	{car_main: 0},
	{car_bg: 0},
	{car_back: 0},
	{car_4_a: 0},
	{car_4_3: 0},
	{car_4_2: 0},
	{car_4_1: 0},
	{car_4: 0},
	{car_3_a: 0},
	{car_3_4: 0},
	{car_3_3: 0},
	{car_3_2: 0},
	{car_3_1: 0},
	{car_3: 0},
	{car_2_a: 0},
	{car_2_3: 0},
	{car_2_2: 0},
	{car_2_1: 0},
	{car_2: 0},
	{car_1_bg: 0},
	{car_1_a: 0},
	{car_1_4: 0},
	{car_1_3: 0},
	{car_1_2: 0},
	{car_1_1: 0},
	{car_1: 0},
	{circular_tw: 0},
	{naming_limit: 0},
	{button_14_3: 0},
	{bike_bg: 0},
	{bike_road: 0},
	{bike_sun: 0},
	{bike_girl: 0},
	{bike_obstacle1: 0},
	{bike_obstacle2: 0},
	{bike_obstacle3: 0},
	{bike_obstacle4: 0},
	{bike_obstacle5: 0},
	{bike_obstacle6: 0},
	{bike_obstacle8: 0},
	{bike_obstacle9: 0},
	{bike_obstacle10: 0},
	{bike_obstacle11: 0},
	{bike_obstacle12: 0},
	{bike_spring: 0},
	{bike_obstacle7: 0},
	{bike_Q1: 0},
	{bike_Q2: 0},
	{bike_Q3: 0},
	{bike_Q4: 0},
	{bike_Q5: 0},
	{bike_Q6: 0},
	{bikeQ_blank_6: 0},
	{bikeQ_blank_5: 0},
	{bikeQ_blank_4: 0},
	{bikeQ_blank_3: 0},
	{bikeQ_blank_2: 0},
	{bikeQ_blank_1: 0},
	{bikeQ_bg: 0},
	{bikeQ_back: 0},
	{bikeQ_ans_d: 0},
	{bikeQ_ans_c: 0},
	{bikeQ_ans_b: 0},
	{bikeQ_ans_a: 0},
	{bikeQ7_send: 0},
	{bikeQ7_ans: 0},
	{bikeQ6_send: 0},
	{bikeQ6_ans: 0},
	{拖放: 0},
	{bikeQ6_4: 0},
	{bikeQ6_3: 0},
	{bikeQ6_2: 0},
	{bikeQ6_1: 0},
	{bikeQ5_send: 0},
	{bikeQ5_ans: 0},
	{bikeQ5_4: 0},
	{bikeQ5_3: 0},
	{bikeQ5_2: 0},
	{bikeQ5_1: 0},
	{bikeQ4_send: 0},
	{bikeQ4_ans: 0},
	{bikeQ4_4: 0},
	{bikeQ4_3: 0},
	{bikeQ4_2: 0},
	{bikeQ4_1: 0},
	{bikeQ3_send: 0},
	{bikeQ3_ans: 0},
	{bikeQ3_4: 0},
	{bikeQ3_3: 0},
	{bikeQ3_2: 0},
	{bikeQ3_1: 0},
	{bikeQ2_send: 0},
	{bikeQ2_ans: 0},
	{bikeQ2_4: 0},
	{bikeQ2_3: 0},
	{bikeQ2_2: 0},
	{bikeQ2_1: 0},
	{bikeQ1_send: 0},
	{bikeQ1_ans: 0},
	{bikeQ1_4: 0},
	{bikeQ1_3: 0},
	{bikeQ1_2: 0},
	{bikeQ1_1: 0},
	{實體: 0},
	{bike_wall: 0},
	{correct_or_not: 0},
	{bike_Q7: 0},
	{bike_sucess: 0},
	{bike_next: 0},
	{sea_bg: 0},
	{screen_move: 0},
	{sea_front: 0},
	{sea_sun: 0},
	{sea_can: 0},
	{sea_mask: 0},
	{sea_net: 0},
	{sea_diaper: 0},
	{sea_bottle: 0},
	{sea_trapa: 0},
	{NameText: 0},
	{sea_learn_bg: 0},
	{sea_1_1: 0},
	{sea_1_2: 0},
	{sea_1_3: 0},
	{sea_1_4: 0},
	{sea_1_ans: 0},
	{sea_2_1: 0},
	{sea_2_2: 0},
	{sea_2_3: 0},
	{sea_2_4: 0},
	{sea_2_ans: 0},
	{sea_3_1: 0},
	{sea_3_2: 0},
	{sea_3_3: 0},
	{sea_3_4: 0},
	{sea_3_ans: 0},
	{sea_4_2: 0},
	{sea_4_1: 0},
	{sea_4_ans: 0},
	{sea_5_1: 0},
	{sea_5_2: 0},
	{sea_5_3: 0},
	{sea_5_4: 0},
	{sea_5_ans: 0},
	{sea_back1: 0},
	{sea_back2: 0},
	{sea_back3: 0},
	{sea_back4: 0},
	{sea_back5: 0},
	{sea_can1: 0},
	{gold_bg: 0},
	{gold_pineapple: 0},
	{gold_oyster: 0},
	{gold_trapa: 0},
	{gold_soy: 0},
	{layout_32: 0},
	{gold_learn_bg: 0},
	{gold_pineapple1: 0},
	{gold_pineapple2: 0},
	{gold_pineapple3: 0},
	{gold_back1: 0},
	{gold_oyster1: 0},
	{gold_oyster2: 0},
	{gold_oyster3: 0},
	{gold_oyster4: 0},
	{gold_oyster5: 0},
	{gold_back2: 0},
	{gold_back3: 0},
	{gold_back4: 0},
	{gold_trapa1: 0},
	{gold_trapa2: 0},
	{gold_soy1: 0},
	{gold_soy2: 0},
	{gold_ans_bg: 0},
	{gold_pineapple_ans: 0},
	{gold_oyster_ans: 0},
	{gold_trapa_ans: 0},
	{gold_soy_ans: 0},
	{gold_ans_back1: 0},
	{gold_ans_back2: 0},
	{gold_ans_back3: 0},
	{gold_ans_back4: 0},
	{layout_34: 0},
	{Video2: 0},
	{marketResultText: 0},
	{phone_finishh: 0},
	{phone_bt_start: 0},
	{phone_bt_next: 0},
	{phone_bt_cu: 0},
	{phone_bt_back: 0},
	{phone_bg: 0},
	{phone_5_ans: 0},
	{phone_5_4: 0},
	{phone_5_3: 0},
	{phone_5_2: 0},
	{phone_5_1: 0},
	{phone_4_ans: 0},
	{phone_4_4: 0},
	{phone_4_3: 0},
	{phone_4_2: 0},
	{phone_4_1: 0},
	{phone_3_ans: 0},
	{phone_3_4: 0},
	{phone_3_3: 0},
	{phone_3_2: 0},
	{phone_3_1: 0},
	{phone_2_ans: 0},
	{phone_2_4: 0},
	{phone_2_3: 0},
	{phone_2_2: 0},
	{phone_2_1: 0},
	{phone_1_ans: 0},
	{phone_1_4: 0},
	{phone_1_3: 0},
	{phone_1_2: 0},
	{phone_1_1: 0},
	{phone_bt_talk: 0},
	{gold_finish: 0},
	{sea_finish: 0},
	{trafficResultText: 0},
	{foodResultText: 0},
	{totalResultText: 0},
	{layout36: 0},
	{gamerule07: 0},
	{gamerule08: 0},
	{finish_card: 0},
	{Sprite5: 0},
	{yearText: 0},
	{monthText: 0},
	{Sprite6: 0},
	{dateText: 0},
	{dire_: 0},
	{AJAX: 0},
	{Share: 0},
	{FileSystem: 0},
	{BinaryData: 0},
	{SaveAsButton: 0},
	{TakeScreenshotButton: 0},
	{date: 0},
	{get_licence_bg: 0},
	{button_get_licence: 0},
	{Text2: 0},
	{layout42: 0},
	{house_bg: 0},
	{house_1: 0},
	{house_3: 0},
	{house_2: 0},
	{Video3: 0},
	{house_4: 0},
	{house_5: 0},
	{market_game1_Q3c2: 0},
	{Sprite: 0},
	{house_learn_bg: 0},
	{house_1_1: 0},
	{house_1_2: 0},
	{house_2_1: 0},
	{house_2_2: 0},
	{house_2_3: 0},
	{house_3_1: 0},
	{house_3_2: 0},
	{house_3_3: 0},
	{house_back1: 0},
	{house_4_1: 0},
	{house_4_2: 0},
	{house_4_3: 0},
	{house_5_1: 0},
	{house_5_2: 0},
	{house_5_3: 0},
	{learn_bar_bt: 0},
	{learn_bar: 0},
	{平台: 0},
	{視野跟隨: 0},
	{screen_move_2: 0},
	{screen_move_3: 0},
	{layout_44: 0},
	{layout_46: 0},
	{gamerule09: 0},
	{layout_49: 0},
	{layout_51: 0},
	{button_again: 0},
	{has_answered: 0},
	{nextbutton_final: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{event_black: 0},
	{dog_land_count: 0},
	{dog_farmer_count: 0},
	{dog_animal_count: 0},
	{dog_storm_count: 0},
	{dog_river_count: 0},
	{dog_factory_count: 0},
	{dog_trash_count: 0},
	{market_game1_count: 0},
	{market_game2_count: 0},
	{market_game3_count: 0},
	{market_game4_count: 0},
	{market_game5_count: 0},
	{game1_tip_change: 0},
	{bike_Q1_count: 0},
	{bike_Q2_count: 0},
	{bike_Q3_count: 0},
	{bike_Q4_count: 0},
	{bike_Q5_count: 0},
	{bike_Q6_count: 0},
	{bike_Q7_count: 0},
	{sea_can_count: 0},
	{sea_mask_count: 0},
	{sea_net_count: 0},
	{sea_diaper_count: 0},
	{sea_bottle_count: 0},
	{game2_tip_change: 0},
	{game3_tip_change: 0},
	{game4_tip_change: 0},
	{market_game5_shineA: 0},
	{market_game5_shineB: 0},
	{market_game5_shineC: 0},
	{market_game5_shineD: 0},
	{market_game5_shineE: 0},
	{market_game5_shineF: 0},
	{market_game5_shineG: 0},
	{car_learn: 0},
	{car_times: 0},
	{a: 0},
	{bikeQ: 0},
	{bikeQ_choose: 0},
	{bikeQ67_1: 0},
	{bikeQ67_2: 0},
	{bikeQ67_3: 0},
	{gold_pineapple_count: 0},
	{gold_oyster_count: 0},
	{gold_trapa_count: 0},
	{gold_soy_count: 0},
	{sea_learn: 0},
	{gold_learn: 0},
	{gold_1_1: 0},
	{gold_1_2: 0},
	{gold_1_3: 0},
	{gold_2_1: 0},
	{gold_2_2: 0},
	{gold_2_3: 0},
	{gold_2_4: 0},
	{gold_2_5: 0},
	{gold_3_1: 0},
	{gold_3_2: 0},
	{gold_4_1: 0},
	{gold_4_2: 0},
	{marketQuestion: 0},
	{marketAnswer: 0},
	{trafficQuestion: 0},
	{trafficAnswer: 0},
	{foodQuestion: 0},
	{foodAnswer: 0},
	{totalQuestion: 0},
	{totalAnswer: 0},
	{phone_test: 0},
	{house_change1_1: 0},
	{house_change1_2: 0},
	{house_change1_3: 0},
	{house_change2_1: 0},
	{house_change2_2: 0},
	{house_learn: 0},
	{house_11: 0},
	{house_12: 0},
	{house_21: 0},
	{house_22: 0},
	{house_23: 0},
	{house_31: 0},
	{house_32: 0},
	{house_33: 0},
	{house_41: 0},
	{house_42: 0},
	{house_43: 0},
	{house_51: 0},
	{house_52: 0},
	{house_53: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	button_2: class extends self.ISpriteInstance {},
	button_3: class extends self.ISpriteInstance {},
	button_04: class extends self.ISpriteInstance {},
	bg_2: class extends self.ISpriteInstance {},
	button_5: class extends self.ISpriteInstance {},
	naming: class extends self.ITextInputInstance {},
	player: class extends self.ITextInstance {},
	chat_03: class extends self.ISpriteInstance {},
	layout3_1: class extends self.ISpriteInstance {},
	dire_1: class extends self.ISpriteInstance {},
	button_6: class extends self.ISpriteInstance {},
	layout3_2: class extends self.ISpriteInstance {},
	layout3_3: class extends self.ISpriteInstance {},
	choo_1: class extends self.ISpriteInstance {},
	choo_2: class extends self.ISpriteInstance {},
	chat_02: class extends self.ISpriteInstance {},
	layout3_3_1: class extends self.ISpriteInstance {},
	gamerule01: class extends self.ISpriteInstance {},
	butterfly: class extends self.ISpriteInstance {},
	hole_01: class extends self.ISpriteInstance {},
	hole_02: class extends self.ISpriteInstance {},
	hole_03: class extends self.ISpriteInstance {},
	hole_04: class extends self.ISpriteInstance {},
	hole_05: class extends self.ISpriteInstance {},
	hole_06: class extends self.ISpriteInstance {},
	hole_07: class extends self.ISpriteInstance {},
	hole_08: class extends self.ISpriteInstance {},
	ans_01: class extends self.ISpriteInstance {},
	ans_02: class extends self.ISpriteInstance {},
	ans_03: class extends self.ISpriteInstance {},
	ans_04: class extends self.ISpriteInstance {},
	ans_05: class extends self.ISpriteInstance {},
	ans_06: class extends self.ISpriteInstance {},
	ans_07: class extends self.ISpriteInstance {},
	ans_08: class extends self.ISpriteInstance {},
	layout3_4_1: class extends self.ISpriteInstance {},
	layout3_3_2: class extends self.ISpriteInstance {},
	layout3_4_2: class extends self.ISpriteInstance {},
	layout3_5: class extends self.ISpriteInstance {},
	bg_1: class extends self.ISpriteInstance {},
	layout3_6: class extends self.ISpriteInstance {},
	layout3_7: class extends self.ISpriteInstance {},
	L5_1: class extends self.ISpriteInstance {},
	L5_2: class extends self.ISpriteInstance {},
	L4: class extends self.ISpriteInstance {},
	layout8_1: class extends self.ISpriteInstance {},
	button_06_1: class extends self.ISpriteInstance {},
	layout8_2: class extends self.ISpriteInstance {},
	gamerule02: class extends self.ISpriteInstance {},
	ani_03: class extends self.ISpriteInstance {},
	chat_03_2: class extends self.ISpriteInstance {},
	layout11_1: class extends self.ISpriteInstance {},
	ani_04: class extends self.ISpriteInstance {},
	button_07_1: class extends self.ISpriteInstance {},
	gamerule03: class extends self.ISpriteInstance {},
	layout15_1: class extends self.ISpriteInstance {},
	ani_05: class extends self.ISpriteInstance {},
	layout_19: class extends self.ISpriteInstance {},
	answer: class extends self.ITextInputInstance {},
	ani_06: class extends self.ISpriteInstance {},
	gamerule04: class extends self.ISpriteInstance {},
	gamerule05: class extends self.ISpriteInstance {},
	layout24: class extends self.ISpriteInstance {},
	layout25: class extends self.ISpriteInstance {},
	ani_17: class extends self.ISpriteInstance {},
	layout27: class extends self.ISpriteInstance {},
	gamerule06: class extends self.ISpriteInstance {},
	sea_game: class extends self.ITextInstance {},
	layout30: class extends self.ISpriteInstance {},
	tip_01: class extends self.ISpriteInstance {},
	button_07_2: class extends self.ISpriteInstance {},
	tip_02: class extends self.ISpriteInstance {},
	tip_03: class extends self.ISpriteInstance {},
	tip_04: class extends self.ISpriteInstance {},
	tip_05: class extends self.ISpriteInstance {},
	tip_06: class extends self.ISpriteInstance {},
	tip_07: class extends self.ISpriteInstance {},
	tip_08: class extends self.ISpriteInstance {},
	dog_window: class extends self.ISpriteInstance {},
	dog_control: class extends self.ISpriteInstance {},
	dog_panel: class extends self.ISpriteInstance {},
	dog_bg: class extends self.ISpriteInstance {},
	dog_factory: class extends self.ISpriteInstance {},
	dog_river: class extends self.ISpriteInstance {},
	dog_animal: class extends self.ISpriteInstance {},
	dog_farmer: class extends self.ISpriteInstance {},
	dog_land: class extends self.ISpriteInstance {},
	dog_storm: class extends self.ISpriteInstance {},
	market_bg: class extends self.ISpriteInstance {},
	market_floor: class extends self.ISpriteInstance {},
	market_sun: class extends self.ISpriteInstance {},
	market_girl: class extends self.ISpriteInstance {},
	market_shop5: class extends self.ISpriteInstance {},
	market_shop4: class extends self.ISpriteInstance {},
	market_shop3: class extends self.ISpriteInstance {},
	market_flag: class extends self.ISpriteInstance {},
	market_shop2: class extends self.ISpriteInstance {},
	market_shop1: class extends self.ISpriteInstance {},
	button_16_1: class extends self.ISpriteInstance {},
	button_16_1_2: class extends self.ISpriteInstance {},
	market_game1: class extends self.ISpriteInstance {},
	market_game1_roof: class extends self.ISpriteInstance {},
	market_game1_girl: class extends self.ISpriteInstance {},
	market_game1_Q1: class extends self.ISpriteInstance {},
	market_game1_Q1d: class extends self.ISpriteInstance {},
	market_game1_Q1c: class extends self.ISpriteInstance {},
	market_game1_Q1a: class extends self.ISpriteInstance {},
	market_game1_accurate: class extends self.ISpriteInstance {},
	market_game1_bullet: class extends self.ISpriteInstance {},
	market_game1_Q1b: class extends self.ISpriteInstance {},
	market_game1_Q2: class extends self.ISpriteInstance {},
	market_game1_Q2a: class extends self.ISpriteInstance {},
	market_game1_Q2b: class extends self.ISpriteInstance {},
	market_game1_Q2c: class extends self.ISpriteInstance {},
	market_game1_Q2d: class extends self.ISpriteInstance {},
	market_game1_Q3: class extends self.ISpriteInstance {},
	market_game1_Q3a: class extends self.ISpriteInstance {},
	market_game1_Q3b: class extends self.ISpriteInstance {},
	market_game1_Q3c: class extends self.ISpriteInstance {},
	market_game1_Q3d: class extends self.ISpriteInstance {},
	market_game1_Q4: class extends self.ISpriteInstance {},
	market_game1_Q4a: class extends self.ISpriteInstance {},
	market_game1_Q4b: class extends self.ISpriteInstance {},
	market_game1_Q4c: class extends self.ISpriteInstance {},
	market_game1_Q4d: class extends self.ISpriteInstance {},
	market_game1_Q5a: class extends self.ISpriteInstance {},
	market_game1_Q5: class extends self.ISpriteInstance {},
	market_game1_Q5b: class extends self.ISpriteInstance {},
	market_game1_Q5c: class extends self.ISpriteInstance {},
	market_game1_Q5d: class extends self.ISpriteInstance {},
	dog_trash: class extends self.ISpriteInstance {},
	dog_storm_teach: class extends self.ISpriteInstance {},
	dog_factory_teach: class extends self.ISpriteInstance {},
	dog_animal_teach: class extends self.ISpriteInstance {},
	dog_land_teach: class extends self.ISpriteInstance {},
	dog_farmer_teach: class extends self.ISpriteInstance {},
	dog_river_teach: class extends self.ISpriteInstance {},
	dog_trash_teach: class extends self.ISpriteInstance {},
	button_go_home: class extends self.IButtonInstance {},
	button_16_2: class extends self.ISpriteInstance {},
	button_16_3: class extends self.ISpriteInstance {},
	button_16_4: class extends self.ISpriteInstance {},
	button_16_5: class extends self.ISpriteInstance {},
	button_1: class extends self.ISpriteInstance {},
	video: class extends self.IWorldInstance {},
	button_14_1: class extends self.ISpriteInstance {},
	market_game1_ans1: class extends self.ISpriteInstance {},
	market_game1_ans2: class extends self.ISpriteInstance {},
	market_game1_ans3: class extends self.ISpriteInstance {},
	market_game1_ans4: class extends self.ISpriteInstance {},
	market_game1_ans5: class extends self.ISpriteInstance {},
	market_game1_finish: class extends self.ISpriteInstance {},
	button_17_back: class extends self.ISpriteInstance {},
	market_game1_tip: class extends self.ISpriteInstance {},
	button_17_next_1: class extends self.ISpriteInstance {},
	button_17_next_2: class extends self.ISpriteInstance {},
	button_17_next_3: class extends self.ISpriteInstance {},
	button_17_next_4: class extends self.ISpriteInstance {},
	market_game2_bg: class extends self.ISpriteInstance {},
	market_game2_tip: class extends self.ISpriteInstance {},
	button_17_1: class extends self.ISpriteInstance {},
	market_game2_Q1: class extends self.ISpriteInstance {},
	market_game2_Q1a: class extends self.ISpriteInstance {},
	market_game2_Q1b: class extends self.ISpriteInstance {},
	market_game2_Q1c: class extends self.ISpriteInstance {},
	market_game2_Q1d: class extends self.ISpriteInstance {},
	market_game2_ans1: class extends self.ISpriteInstance {},
	button_17_1_next1: class extends self.ISpriteInstance {},
	market_game2_Q2: class extends self.ISpriteInstance {},
	market_game2_Q2a: class extends self.ISpriteInstance {},
	market_game2_Q2b: class extends self.ISpriteInstance {},
	market_game2_Q2c: class extends self.ISpriteInstance {},
	market_game2_Q2d: class extends self.ISpriteInstance {},
	button_17_1_next2: class extends self.ISpriteInstance {},
	market_game2_ans2: class extends self.ISpriteInstance {},
	market_game2_Q3: class extends self.ISpriteInstance {},
	market_game2_Q3a: class extends self.ISpriteInstance {},
	market_game2_Q3b: class extends self.ISpriteInstance {},
	market_game2_Q3c: class extends self.ISpriteInstance {},
	market_game2_Q3d: class extends self.ISpriteInstance {},
	button_17_1_next3: class extends self.ISpriteInstance {},
	market_game2_ans3: class extends self.ISpriteInstance {},
	market_game2_Q4a: class extends self.ISpriteInstance {},
	market_game2_Q4: class extends self.ISpriteInstance {},
	market_game2_Q4b: class extends self.ISpriteInstance {},
	market_game2_Q4c: class extends self.ISpriteInstance {},
	market_game2_Q4d: class extends self.ISpriteInstance {},
	market_game2_ans4: class extends self.ISpriteInstance {},
	button_17_1_next4: class extends self.ISpriteInstance {},
	market_game2_finish: class extends self.ISpriteInstance {},
	button_17_1_back: class extends self.ISpriteInstance {},
	market_game3_Q1: class extends self.ISpriteInstance {},
	market_game3_Q1a: class extends self.ISpriteInstance {},
	market_game3_Q1b: class extends self.ISpriteInstance {},
	market_game3_Q1c: class extends self.ISpriteInstance {},
	market_game3_Q1d: class extends self.ISpriteInstance {},
	market_game3_ans1: class extends self.ISpriteInstance {},
	market_game3_Q2: class extends self.ISpriteInstance {},
	market_game3_Q2a: class extends self.ISpriteInstance {},
	market_game3_Q2b: class extends self.ISpriteInstance {},
	market_game3_Q2c: class extends self.ISpriteInstance {},
	market_game3_Q2d: class extends self.ISpriteInstance {},
	market_game3_ans2: class extends self.ISpriteInstance {},
	button_17_2next1: class extends self.ISpriteInstance {},
	market_game3_Q3: class extends self.ISpriteInstance {},
	button_17_2next2: class extends self.ISpriteInstance {},
	button_17_2next3: class extends self.ISpriteInstance {},
	market_game3_Q3a: class extends self.ISpriteInstance {},
	market_game3_Q3b: class extends self.ISpriteInstance {},
	market_game3_Q3c: class extends self.ISpriteInstance {},
	market_game3_Q3d: class extends self.ISpriteInstance {},
	market_game3_ans3: class extends self.ISpriteInstance {},
	market_game3_Q4: class extends self.ISpriteInstance {},
	market_game3_Q4a: class extends self.ISpriteInstance {},
	market_game3_Q4b: class extends self.ISpriteInstance {},
	market_game3_Q4c: class extends self.ISpriteInstance {},
	market_game3_Q4d: class extends self.ISpriteInstance {},
	button_17_2next4: class extends self.ISpriteInstance {},
	market_game3_ans4: class extends self.ISpriteInstance {},
	market_game3_Q5: class extends self.ISpriteInstance {},
	market_game3_Q5a: class extends self.ISpriteInstance {},
	market_game3_Q5b: class extends self.ISpriteInstance {},
	market_game3_Q5c: class extends self.ISpriteInstance {},
	market_game3_Q5d: class extends self.ISpriteInstance {},
	market_game3_ans5: class extends self.ISpriteInstance {},
	button_17_2next5: class extends self.ISpriteInstance {},
	market_game3_finish: class extends self.ISpriteInstance {},
	button_17_2_back: class extends self.ISpriteInstance {},
	market_game3_tip: class extends self.ISpriteInstance {},
	button_17_2: class extends self.ISpriteInstance {},
	butterfly_finish: class extends self.ISpriteInstance {},
	button_07_3: class extends self.ISpriteInstance {},
	button_14_2: class extends self.ISpriteInstance {},
	dog_finish: class extends self.ISpriteInstance {},
	market_game4_Q1: class extends self.ISpriteInstance {},
	market_game4_Q1a: class extends self.ISpriteInstance {},
	market_game4_Q1b: class extends self.ISpriteInstance {},
	market_game4_Q1c: class extends self.ISpriteInstance {},
	market_game4_Q1d: class extends self.ISpriteInstance {},
	market_game4_Q1e: class extends self.ISpriteInstance {},
	market_game5_bg: class extends self.ISpriteInstance {},
	market_game5_Q1a: class extends self.ISpriteInstance {},
	market_game5_Q1b: class extends self.ISpriteInstance {},
	market_game5_Q1c: class extends self.ISpriteInstance {},
	market_game5_Q1d: class extends self.ISpriteInstance {},
	market_game5_Q1e: class extends self.ISpriteInstance {},
	market_game5_Q1f: class extends self.ISpriteInstance {},
	market_game5_Q1g: class extends self.ISpriteInstance {},
	market_game5_ans1: class extends self.ISpriteInstance {},
	button_17_4next1: class extends self.ISpriteInstance {},
	market_game5_Q2a: class extends self.ISpriteInstance {},
	market_game5_Q2b: class extends self.ISpriteInstance {},
	market_game5_Q2c: class extends self.ISpriteInstance {},
	market_game5_ans2: class extends self.ISpriteInstance {},
	button_17_4next2: class extends self.ISpriteInstance {},
	button_17_4next3: class extends self.ISpriteInstance {},
	market_game5_Q3a: class extends self.ISpriteInstance {},
	market_game5_Q3b: class extends self.ISpriteInstance {},
	market_game5_Q3c: class extends self.ISpriteInstance {},
	market_game5_ans3: class extends self.ISpriteInstance {},
	market_game4_ans_but: class extends self.ISpriteInstance {},
	market_game4_ans: class extends self.ISpriteInstance {},
	button_17_3next1: class extends self.ISpriteInstance {},
	button_17_3next2: class extends self.ISpriteInstance {},
	button_17_3next3: class extends self.ISpriteInstance {},
	button_17_3next4: class extends self.ISpriteInstance {},
	market_game4_Q2: class extends self.ISpriteInstance {},
	market_game4_Q2a: class extends self.ISpriteInstance {},
	market_game4_Q2b: class extends self.ISpriteInstance {},
	market_game4_Q2c: class extends self.ISpriteInstance {},
	market_game4_Q2d: class extends self.ISpriteInstance {},
	market_game4_Q2e: class extends self.ISpriteInstance {},
	market_game4_ans2_but: class extends self.ISpriteInstance {},
	market_game4_ans2: class extends self.ISpriteInstance {},
	market_game4_Q3: class extends self.ISpriteInstance {},
	market_game4_Q3a: class extends self.ISpriteInstance {},
	market_game4_Q4b: class extends self.ISpriteInstance {},
	market_game4_Q3c: class extends self.ISpriteInstance {},
	market_game4_Q3d: class extends self.ISpriteInstance {},
	market_game4_Q3e: class extends self.ISpriteInstance {},
	market_game4_ans3_but: class extends self.ISpriteInstance {},
	market_game4_ans3: class extends self.ISpriteInstance {},
	market_game4_Q4: class extends self.ISpriteInstance {},
	market_game4_Q4a: class extends self.ISpriteInstance {},
	market_game4_Q4c: class extends self.ISpriteInstance {},
	market_game4_Q4d: class extends self.ISpriteInstance {},
	market_game4_Q4e: class extends self.ISpriteInstance {},
	market_game4_ans4_but: class extends self.ISpriteInstance {},
	market_game4_ans4: class extends self.ISpriteInstance {},
	market_game4_Q5: class extends self.ISpriteInstance {},
	market_game4_Q5a: class extends self.ISpriteInstance {},
	market_game4_Q5b: class extends self.ISpriteInstance {},
	market_game4_Q5c: class extends self.ISpriteInstance {},
	market_game4_Q5d: class extends self.ISpriteInstance {},
	market_game4_Q5e: class extends self.ISpriteInstance {},
	market_game4_ans5_but: class extends self.ISpriteInstance {},
	market_game4_ans5: class extends self.ISpriteInstance {},
	button_17_3next5: class extends self.ISpriteInstance {},
	market_game4_Q3b: class extends self.ISpriteInstance {},
	button_17_3: class extends self.ISpriteInstance {},
	button_17_3_back: class extends self.ISpriteInstance {},
	market_game4_finish: class extends self.ISpriteInstance {},
	market_game4_tip: class extends self.ISpriteInstance {},
	button_17_4: class extends self.ISpriteInstance {},
	button_17: class extends self.ISpriteInstance {},
	button_17_next_5: class extends self.ISpriteInstance {},
	car_main: class extends self.ISpriteInstance {},
	car_bg: class extends self.ISpriteInstance {},
	car_back: class extends self.ISpriteInstance {},
	car_4_a: class extends self.ISpriteInstance {},
	car_4_3: class extends self.ISpriteInstance {},
	car_4_2: class extends self.ISpriteInstance {},
	car_4_1: class extends self.ISpriteInstance {},
	car_4: class extends self.ISpriteInstance {},
	car_3_a: class extends self.ISpriteInstance {},
	car_3_4: class extends self.ISpriteInstance {},
	car_3_3: class extends self.ISpriteInstance {},
	car_3_2: class extends self.ISpriteInstance {},
	car_3_1: class extends self.ISpriteInstance {},
	car_3: class extends self.ISpriteInstance {},
	car_2_a: class extends self.ISpriteInstance {},
	car_2_3: class extends self.ISpriteInstance {},
	car_2_2: class extends self.ISpriteInstance {},
	car_2_1: class extends self.ISpriteInstance {},
	car_2: class extends self.ISpriteInstance {},
	car_1_bg: class extends self.ISpriteInstance {},
	car_1_a: class extends self.ISpriteInstance {},
	car_1_4: class extends self.ISpriteInstance {},
	car_1_3: class extends self.ISpriteInstance {},
	car_1_2: class extends self.ISpriteInstance {},
	car_1_1: class extends self.ISpriteInstance {},
	car_1: class extends self.ISpriteInstance {},
	circular_tw: class extends self.ISpriteInstance {},
	naming_limit: class extends self.ISpriteInstance {},
	button_14_3: class extends self.ISpriteInstance {},
	bike_bg: class extends self.ISpriteInstance {},
	bike_road: class extends self.ISpriteInstance {},
	bike_sun: class extends self.ISpriteInstance {},
	bike_girl: class extends self.ISpriteInstance {},
	bike_obstacle1: class extends self.ISpriteInstance {},
	bike_obstacle2: class extends self.ISpriteInstance {},
	bike_obstacle3: class extends self.ISpriteInstance {},
	bike_obstacle4: class extends self.ISpriteInstance {},
	bike_obstacle5: class extends self.ISpriteInstance {},
	bike_obstacle6: class extends self.ISpriteInstance {},
	bike_obstacle8: class extends self.ISpriteInstance {},
	bike_obstacle9: class extends self.ISpriteInstance {},
	bike_obstacle10: class extends self.ISpriteInstance {},
	bike_obstacle11: class extends self.ISpriteInstance {},
	bike_obstacle12: class extends self.ISpriteInstance {},
	bike_spring: class extends self.ISpriteInstance {},
	bike_obstacle7: class extends self.ISpriteInstance {},
	bike_Q1: class extends self.ISpriteInstance {},
	bike_Q2: class extends self.ISpriteInstance {},
	bike_Q3: class extends self.ISpriteInstance {},
	bike_Q4: class extends self.ISpriteInstance {},
	bike_Q5: class extends self.ISpriteInstance {},
	bike_Q6: class extends self.ISpriteInstance {},
	bikeQ_blank_6: class extends self.ISpriteInstance {},
	bikeQ_blank_5: class extends self.ISpriteInstance {},
	bikeQ_blank_4: class extends self.ISpriteInstance {},
	bikeQ_blank_3: class extends self.ISpriteInstance {},
	bikeQ_blank_2: class extends self.ISpriteInstance {},
	bikeQ_blank_1: class extends self.ISpriteInstance {},
	bikeQ_bg: class extends self.ISpriteInstance {},
	bikeQ_back: class extends self.ISpriteInstance {},
	bikeQ_ans_d: class extends self.ISpriteInstance {},
	bikeQ_ans_c: class extends self.ISpriteInstance {},
	bikeQ_ans_b: class extends self.ISpriteInstance {},
	bikeQ_ans_a: class extends self.ISpriteInstance {},
	bikeQ7_send: class extends self.ISpriteInstance {},
	bikeQ7_ans: class extends self.ISpriteInstance {},
	bikeQ6_send: class extends self.ISpriteInstance {},
	bikeQ6_ans: class extends self.ISpriteInstance {},
	bikeQ6_4: class extends self.ISpriteInstance {},
	bikeQ6_3: class extends self.ISpriteInstance {},
	bikeQ6_2: class extends self.ISpriteInstance {},
	bikeQ6_1: class extends self.ISpriteInstance {},
	bikeQ5_send: class extends self.ISpriteInstance {},
	bikeQ5_ans: class extends self.ISpriteInstance {},
	bikeQ5_4: class extends self.ISpriteInstance {},
	bikeQ5_3: class extends self.ISpriteInstance {},
	bikeQ5_2: class extends self.ISpriteInstance {},
	bikeQ5_1: class extends self.ISpriteInstance {},
	bikeQ4_send: class extends self.ISpriteInstance {},
	bikeQ4_ans: class extends self.ISpriteInstance {},
	bikeQ4_4: class extends self.ISpriteInstance {},
	bikeQ4_3: class extends self.ISpriteInstance {},
	bikeQ4_2: class extends self.ISpriteInstance {},
	bikeQ4_1: class extends self.ISpriteInstance {},
	bikeQ3_send: class extends self.ISpriteInstance {},
	bikeQ3_ans: class extends self.ISpriteInstance {},
	bikeQ3_4: class extends self.ISpriteInstance {},
	bikeQ3_3: class extends self.ISpriteInstance {},
	bikeQ3_2: class extends self.ISpriteInstance {},
	bikeQ3_1: class extends self.ISpriteInstance {},
	bikeQ2_send: class extends self.ISpriteInstance {},
	bikeQ2_ans: class extends self.ISpriteInstance {},
	bikeQ2_4: class extends self.ISpriteInstance {},
	bikeQ2_3: class extends self.ISpriteInstance {},
	bikeQ2_2: class extends self.ISpriteInstance {},
	bikeQ2_1: class extends self.ISpriteInstance {},
	bikeQ1_send: class extends self.ISpriteInstance {},
	bikeQ1_ans: class extends self.ISpriteInstance {},
	bikeQ1_4: class extends self.ISpriteInstance {},
	bikeQ1_3: class extends self.ISpriteInstance {},
	bikeQ1_2: class extends self.ISpriteInstance {},
	bikeQ1_1: class extends self.ISpriteInstance {},
	bike_wall: class extends self.ISpriteInstance {},
	correct_or_not: class extends self.ISpriteInstance {},
	bike_Q7: class extends self.ISpriteInstance {},
	bike_sucess: class extends self.ISpriteInstance {},
	bike_next: class extends self.ISpriteInstance {},
	sea_bg: class extends self.ISpriteInstance {},
	screen_move: class extends self.ISpriteInstance {},
	sea_front: class extends self.ISpriteInstance {},
	sea_sun: class extends self.ISpriteInstance {},
	sea_can: class extends self.ISpriteInstance {},
	sea_mask: class extends self.ISpriteInstance {},
	sea_net: class extends self.ISpriteInstance {},
	sea_diaper: class extends self.ISpriteInstance {},
	sea_bottle: class extends self.ISpriteInstance {},
	sea_trapa: class extends self.ISpriteInstance {},
	NameText: class extends self.ITextInstance {},
	sea_learn_bg: class extends self.ISpriteInstance {},
	sea_1_1: class extends self.ISpriteInstance {},
	sea_1_2: class extends self.ISpriteInstance {},
	sea_1_3: class extends self.ISpriteInstance {},
	sea_1_4: class extends self.ISpriteInstance {},
	sea_1_ans: class extends self.ISpriteInstance {},
	sea_2_1: class extends self.ISpriteInstance {},
	sea_2_2: class extends self.ISpriteInstance {},
	sea_2_3: class extends self.ISpriteInstance {},
	sea_2_4: class extends self.ISpriteInstance {},
	sea_2_ans: class extends self.ISpriteInstance {},
	sea_3_1: class extends self.ISpriteInstance {},
	sea_3_2: class extends self.ISpriteInstance {},
	sea_3_3: class extends self.ISpriteInstance {},
	sea_3_4: class extends self.ISpriteInstance {},
	sea_3_ans: class extends self.ISpriteInstance {},
	sea_4_2: class extends self.ISpriteInstance {},
	sea_4_1: class extends self.ISpriteInstance {},
	sea_4_ans: class extends self.ISpriteInstance {},
	sea_5_1: class extends self.ISpriteInstance {},
	sea_5_2: class extends self.ISpriteInstance {},
	sea_5_3: class extends self.ISpriteInstance {},
	sea_5_4: class extends self.ISpriteInstance {},
	sea_5_ans: class extends self.ISpriteInstance {},
	sea_back1: class extends self.ISpriteInstance {},
	sea_back2: class extends self.ISpriteInstance {},
	sea_back3: class extends self.ISpriteInstance {},
	sea_back4: class extends self.ISpriteInstance {},
	sea_back5: class extends self.ISpriteInstance {},
	sea_can1: class extends self.ISpriteInstance {},
	gold_bg: class extends self.ISpriteInstance {},
	gold_pineapple: class extends self.ISpriteInstance {},
	gold_oyster: class extends self.ISpriteInstance {},
	gold_trapa: class extends self.ISpriteInstance {},
	gold_soy: class extends self.ISpriteInstance {},
	layout_32: class extends self.ISpriteInstance {},
	gold_learn_bg: class extends self.ISpriteInstance {},
	gold_pineapple1: class extends self.ISpriteInstance {},
	gold_pineapple2: class extends self.ISpriteInstance {},
	gold_pineapple3: class extends self.ISpriteInstance {},
	gold_back1: class extends self.ISpriteInstance {},
	gold_oyster1: class extends self.ISpriteInstance {},
	gold_oyster2: class extends self.ISpriteInstance {},
	gold_oyster3: class extends self.ISpriteInstance {},
	gold_oyster4: class extends self.ISpriteInstance {},
	gold_oyster5: class extends self.ISpriteInstance {},
	gold_back2: class extends self.ISpriteInstance {},
	gold_back3: class extends self.ISpriteInstance {},
	gold_back4: class extends self.ISpriteInstance {},
	gold_trapa1: class extends self.ISpriteInstance {},
	gold_trapa2: class extends self.ISpriteInstance {},
	gold_soy1: class extends self.ISpriteInstance {},
	gold_soy2: class extends self.ISpriteInstance {},
	gold_ans_bg: class extends self.ISpriteInstance {},
	gold_pineapple_ans: class extends self.ISpriteInstance {},
	gold_oyster_ans: class extends self.ISpriteInstance {},
	gold_trapa_ans: class extends self.ISpriteInstance {},
	gold_soy_ans: class extends self.ISpriteInstance {},
	gold_ans_back1: class extends self.ISpriteInstance {},
	gold_ans_back2: class extends self.ISpriteInstance {},
	gold_ans_back3: class extends self.ISpriteInstance {},
	gold_ans_back4: class extends self.ISpriteInstance {},
	layout_34: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	marketResultText: class extends self.ITextInstance {},
	phone_finishh: class extends self.ISpriteInstance {},
	phone_bt_start: class extends self.ISpriteInstance {},
	phone_bt_next: class extends self.ISpriteInstance {},
	phone_bt_cu: class extends self.ISpriteInstance {},
	phone_bt_back: class extends self.ISpriteInstance {},
	phone_bg: class extends self.ISpriteInstance {},
	phone_5_ans: class extends self.ISpriteInstance {},
	phone_5_4: class extends self.ISpriteInstance {},
	phone_5_3: class extends self.ISpriteInstance {},
	phone_5_2: class extends self.ISpriteInstance {},
	phone_5_1: class extends self.ISpriteInstance {},
	phone_4_ans: class extends self.ISpriteInstance {},
	phone_4_4: class extends self.ISpriteInstance {},
	phone_4_3: class extends self.ISpriteInstance {},
	phone_4_2: class extends self.ISpriteInstance {},
	phone_4_1: class extends self.ISpriteInstance {},
	phone_3_ans: class extends self.ISpriteInstance {},
	phone_3_4: class extends self.ISpriteInstance {},
	phone_3_3: class extends self.ISpriteInstance {},
	phone_3_2: class extends self.ISpriteInstance {},
	phone_3_1: class extends self.ISpriteInstance {},
	phone_2_ans: class extends self.ISpriteInstance {},
	phone_2_4: class extends self.ISpriteInstance {},
	phone_2_3: class extends self.ISpriteInstance {},
	phone_2_2: class extends self.ISpriteInstance {},
	phone_2_1: class extends self.ISpriteInstance {},
	phone_1_ans: class extends self.ISpriteInstance {},
	phone_1_4: class extends self.ISpriteInstance {},
	phone_1_3: class extends self.ISpriteInstance {},
	phone_1_2: class extends self.ISpriteInstance {},
	phone_1_1: class extends self.ISpriteInstance {},
	phone_bt_talk: class extends self.ISpriteInstance {},
	gold_finish: class extends self.ISpriteInstance {},
	sea_finish: class extends self.ISpriteInstance {},
	trafficResultText: class extends self.ITextInstance {},
	foodResultText: class extends self.ITextInstance {},
	totalResultText: class extends self.ITextInstance {},
	layout36: class extends self.ISpriteInstance {},
	gamerule07: class extends self.ISpriteInstance {},
	gamerule08: class extends self.ISpriteInstance {},
	finish_card: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	yearText: class extends self.ITextInstance {},
	monthText: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	dateText: class extends self.ITextInstance {},
	dire_: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Share: class extends self.IInstance {},
	FileSystem: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	SaveAsButton: class extends self.IButtonInstance {},
	TakeScreenshotButton: class extends self.IButtonInstance {},
	date: class extends self.IInstance {},
	get_licence_bg: class extends self.ISpriteInstance {},
	button_get_licence: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	layout42: class extends self.ISpriteInstance {},
	house_bg: class extends self.ISpriteInstance {},
	house_1: class extends self.ISpriteInstance {},
	house_3: class extends self.ISpriteInstance {},
	house_2: class extends self.ISpriteInstance {},
	Video3: class extends self.IWorldInstance {},
	house_4: class extends self.ISpriteInstance {},
	house_5: class extends self.ISpriteInstance {},
	market_game1_Q3c2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	house_learn_bg: class extends self.ISpriteInstance {},
	house_1_1: class extends self.ISpriteInstance {},
	house_1_2: class extends self.ISpriteInstance {},
	house_2_1: class extends self.ISpriteInstance {},
	house_2_2: class extends self.ISpriteInstance {},
	house_2_3: class extends self.ISpriteInstance {},
	house_3_1: class extends self.ISpriteInstance {},
	house_3_2: class extends self.ISpriteInstance {},
	house_3_3: class extends self.ISpriteInstance {},
	house_back1: class extends self.ISpriteInstance {},
	house_4_1: class extends self.ISpriteInstance {},
	house_4_2: class extends self.ISpriteInstance {},
	house_4_3: class extends self.ISpriteInstance {},
	house_5_1: class extends self.ISpriteInstance {},
	house_5_2: class extends self.ISpriteInstance {},
	house_5_3: class extends self.ISpriteInstance {},
	learn_bar_bt: class extends self.ISpriteInstance {},
	learn_bar: class extends self.ISpriteInstance {},
	screen_move_2: class extends self.ISpriteInstance {},
	screen_move_3: class extends self.ISpriteInstance {},
	layout_44: class extends self.ISpriteInstance {},
	layout_46: class extends self.ISpriteInstance {},
	gamerule09: class extends self.ISpriteInstance {},
	layout_49: class extends self.ISpriteInstance {},
	layout_51: class extends self.ISpriteInstance {},
	button_again: class extends self.ISpriteInstance {},
	nextbutton_final: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}